### ISSUE TITLE
Agregar enlace a README de documentación del API

### ISSUE THREAD

**Issue by robertoissc** [epconccs/numeros-a-letras#27]
**Describe el problema**
Agregar enlace de Swagger a README para documentación y prueba de api.

**Comment by robertoissc** [comment]
@andreitg ¿Será bueno borrar la documentación actual del README y solo mantenerla en Swagger?

**Comment by andreitg** [comment]
@robertoissc Yo creo que sí, para evitar tener versiones desactualizadas o diferentes de la documentación en ambos lados. Mejor sí la quitamos del README y hacemos referencia a Swagger.
