### ISSUE TITLE
Corregir URL de prueba en README

### ISSUE THREAD

**Issue by robertoissc** [epconccs/numeros-a-letras#49]
**Describe el bug**
En el README se especifica la URL https://nal.azurewebsites.net/api/NAL/256/ para probar. Esta URL ya no es válida y arroja un error 404 debido a que parámetros path ya no son aceptados por el API.

**Comportamiento esperado**
README con URL de prueba con parámetros query que genere la conversión a letra del número 256.
https://nal.azurewebsites.net/api/NAL?num=256

**Comment by andreitg** [comment]
¡Listo! Muchas gracias @robertoissc
